export default function HomePage() {
  return (
    <>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
      <h1>some text</h1>
    </>
  );
}
