import type { Metadata } from "next";
import "./globals.scss";

import { SessionProvider } from "next-auth/react";
import { Nunito } from "next/font/google";

import { Providers } from "../components/providers/Providers";
import { auth } from "../config/auth";

const nunito = Nunito({
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={nunito.className}>
        <SessionProvider session={session}>
          <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
